---
name: Ubuntu PHP 7.4-8.2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php-7_4:
    uses: ./.github/workflows/reusable-build-php.yml
    with:
      php_version: "7.4"
      container: "ubuntu:focal"

  php-8_0:
    uses: ./.github/workflows/reusable-build-php.yml
    with:
      php_version: "8.0"
      container: "ubuntu:focal"

  php-8_1:
    uses: ./.github/workflows/reusable-build-php.yml
    with:
      php_version: "8.1"
      container: "ubuntu:22.04"

  php-8_2:
    uses: ./.github/workflows/reusable-build-php.yml
    with:
      php_version: "8.2"
      container: "ubuntu:22.04"
